In [1]:
import pandas as pd
import json
import requests
import urllib
from io import StringIO

In [2]:
fifa_url = 'https://en.wikipedia.org/wiki/FIFA_World_Cup'

In [3]:
fifa_response = requests.get(fifa_url)

In [4]:
fifa_response.status_code

200

In [5]:
fifa_tables = pd.read_html(StringIO(fifa_response.text))

In [6]:
type(fifa_tables), len(fifa_tables)

(list, 40)

In [7]:
fifa_tables[3]

       Year                          Hosts Venues/ Cities Total attendance †  \
       Year                          Hosts Venues/ Cities Total attendance †
0      1930                        Uruguay            3/1           590549.0
1      1934                          Italy            8/8           363000.0
2      1938                         France           10/9           375700.0
3      1950                         Brazil            6/6          1045246.0
4      1954                    Switzerland            6/6           768607.0
5      1958                         Sweden          12/12           819810.0
6      1962                          Chile            4/4           893172.0
7      1966                        England            8/7          1563135.0
8      1970                         Mexico            5/5          1603975.0
9      1974                   West Germany            9/9          1865753.0
10     1978                      Argentina            6/5          1545791.0
11     1982                          Spain          17/14          2109723.0
12     1986                         Mexico          12/11          2394031.0
13     1990                          Italy          12/12          2516215.0
14     1994                  United States            9/9          3587538.0
15     1998                         France          10/10          2785100.0
16     2002             South Korea  Japan          20/20          2705197.0
17     2006                        Germany          12/12          3359439.0
18     2010                   South Africa           10/9          3178856.0
19     2014                         Brazil          12/12          3429873.0
20     2018                         Russia          12/11          3031768.0
21     2022                          Qatar            8/5          3404252.0
22     2026  Canada  Mexico  United States          16/16                NaN
23     2030  Morocco  Portugal  Spain[n 1]          20/20                NaN
24     2034                   Saudi Arabia           15/5                NaN
25  Overall                        Overall        Overall         43936730.0

   Matches Average attendance Highest attendances ‡  \
   Matches Average attendance                Number
0       18            32808.0                 79867
1       17            21353.0                 55000
2       18            20872.0                 58455
3       22            47511.0           173,850[96]
4       26            29562.0                 62500
5       35            23423.0                 50928
6       32            27912.0                 76594
7       32            48848.0                 98270
8       32            50124.0                108192
9       38            49099.0                 83168
10      38            40679.0                 71712
11      52            40572.0                 95500
12      52            46039.0                114600
13      52            48389.0                 74765
14      52            68991.0                 94194
15      64            43517.0                 80000
16      64            42269.0                 69029
17      64            52491.0                 72000
18      64            49670.0                 84490
19      64            53592.0                 74738
20      64            47371.0                 78011
21      64            53191.0                 88966
22     104                NaN                   NaN
23     104                NaN                   NaN
24     104                NaN                   NaN
25     964            45577.0           173,850[96]

                                             \
                                      Venue
0            Estadio Centenario, Montevideo
1                Stadio Nazionale PNF, Rome
2              Olympique de Colombes, Paris
3          Maracanã Stadium, Rio de Janeiro
4                    Wankdorf Stadium, Bern
5                Ullevi Stadium, Gothenburg
6                Estadio Nacional, Santiago
7                   Wembley Stadium, London
8               Estadio Azteca, Mexico City
9                    Olympiastadion, Munich
10         Estadio Monumental, Buenos Aires
11                      Camp Nou, Barcelona
12              Estadio Azteca, Mexico City
13                          San Siro, Milan
14          Rose Bowl, Pasadena, California
15             Stade de France, Saint-Denis
16   International Stadium, Yokohama, Japan
17                   Olympiastadion, Berlin
18                Soccer City, Johannesburg
19         Maracanã Stadium, Rio de Janeiro
20                 Luzhniki Stadium, Moscow
21                   Lusail Stadium, Lusail
22                                      NaN
23                                      NaN
24                                      NaN
25  Maracanã Stadium, Rio de Janeiro (1950)


                                              Game(s)
0                  Uruguay 6–1 Yugoslavia, semi-final
1                     Italy 2–1 Czechoslovakia, final
2                     France 1–3 Italy, quarter-final
3                  Brazil 1–2 Uruguay, deciding match
4                     West Germany 3–2 Hungary, final
5                Brazil 2–0 Soviet Union, group stage
6                        Brazil 4–2 Chile, semi-final
7                     England 2–0 France, group stage
8                     Mexico 1–0 Belgium, group stage
9                 West Germany 1–0 Chile, group stage
10                   Italy 1–0 Argentina, group stage
11               Argentina 0–1 Belgium, Opening match
12  Two matches, including the final, all at Estad...
13           West Germany 4–1 Yugoslavia, group stage
14                     Brazil 0–0 (3–2p) Italy, final
15  Four matches, including the final, all at Stad...
16                          Brazil 2–0 Germany, final
17                Five matches, all at Olympiastadion
18  Two matches, including the final, all at Socce...
19                       Germany 1–0 Argentina, final
20  Seven matches, including the final, all at Luz...
21  Three matches, including the final, all at Lus...
22                                                NaN
23                                                NaN
24                                                NaN
25                                                NaN

In [8]:
airport_endpoint = 'https://aviationweather.gov/api/data/airport'

In [9]:
query = '?ids={}&format={}'.format('@OH', 'json')

In [10]:
airport_response = requests.get(airport_endpoint + query)
airport_response.status_code

200

In [11]:
airport_dat = json.loads(airport_response.text)
airport_df = pd.DataFrame(airport_dat)
airport_df.head()

,id,icaoId,iataId,faaId,name,state,country,source,type,lat,...,rwyNum,rwyLength,rwyType,services,tower,beacon,operations,passengers,freqs,priority
0,12976,K10G,-,10G,MILLERSBURG/HOLMES COUNTY,OH,US,FAA,ARP,40.5367,...,1,M,A,S,None,B,0,None,-,4
1,13098,K2G2,-,2G2,STEUBENVILLE/GEARY A BATES/JEFFERSON COUNTY AI...,OH,US,FAA,ARP,40.3606,...,1,M,A,S,None,B,0,None,-,5
2,12991,K4I3,-,4I3,MOUNT VERNON/KNOX COUNTY,OH,US,FAA,ARP,40.3289,...,1,M,A,S,None,B,0,None,-,4
3,12608,KAKR,AKC,AKR,AKRON/AKRON FULTON INTL,OH,US,FAA,ARP,41.0374,...,1,M,A,S,None,None,0,None,-,5
4,13165,KAMT,-,AMT,WEST UNION/ALEXANDER SALAMON,OH,US,FAA,ARP,38.8517,...,1,M,A,None,None,B,0,None,-,4